stages:
  complete-hackernews:
    cmd: datazimmer run-step complete-hackernews
    deps:
    - src/hackernews.py
    params:
    - zimmer.yaml:
      - cron_bumps.complete-hackernews
    outs:
    - data/articles/hackernews/complete/post:
        persist: true
