stages:
  complete-hackernews:
    cmd: dz run-step hackernews complete
    deps:
    - src/hackernews.py
    outs:
    - data/articles/hackernews/complete:
        persist: true
    params:
    - zimmer.yaml:
      - aswan_projects.hackernews.current_leaf
  complete-repec:
    cmd: dz run-step repec complete
    deps:
    - src/repec.py
    outs:
    - data/articles/repec/complete:
        persist: true
