name: Scheduled Run
on:
  schedule:
  - cron: 20 * * * *
jobs:
  cron_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install dependencies
      run: python -m pip install --upgrade pip;pip install -r requirements.txt
    - name: Setup Git
      run: git config --global init.defaultBranch main;git config --global user.email
        "leo@dumbartonserum.com";git config --global user.name "Leo Dumbarton"
    - name: Setup Auth
      env:
        DVC_LOCAL_CONF: ${{ secrets.DVC_LOCAL }}
      run: echo "$DVC_LOCAL_CONF" > .dvc/config.local
    - name: Bump crons
      env:
        CRON_TRIGGER: ${{ github.event.schedule }}
        ZIMMER_REGISTRY: ${{ secrets.ZIMMER_REGISTRY }}
      run: inv build && inv run-cronjobs && inv publish-data
